// Heimdall.Web/ClientApp/app/components/shared/loading.component.ts
﻿import { Component } from '@angular/core';

@Component({
    selector: 'loading',
    templateUrl: './loading.component.html'
})
export class LoadingComponent {
}
﻿<div class="progress">
    <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 100%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
</div>

// Heimdall.Web/app/components/loading.tsx
﻿import * as React from "react";

export class Loading extends React.Component<{}, {}> {
    constructor(props: any) {
        super(props);
    }

    render() {
        return <div className="progress">
            <div className="progress-bar progress-bar-info progress-bar-striped" role="progressbar"
                aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style={{ width: '100%' }}>
                <span className="sr-only">Loading...</span>
            </div>
        </div>;
    }
}
